# 4장 머신러닝에 필요한 수학의 기본

## 4.1 벡터

In [1]:
import numpy as np   #numpy 라이브러리 import 

In [2]:
a = np.array([2,1])
print(a)

[2 1]


In [3]:
type(a)

numpy.ndarray

In [4]:
c=np.array([[1,2],[3,4]]) #2X2 2차원 행렬
print(c)

[[1 2]
 [3 4]]


In [5]:
d=np.array([[1],[2]]) #2X1 2차원 행렬
print(d)

[[1]
 [2]]


In [6]:
print(d.T)   #전치로 나타내기

[[1 2]]


In [7]:
a = np.array([2,1])
b = np.array([1,3])
print(a+b)         #벡터의 덧셈

[3 4]


In [8]:
a = np.array([2,1])
b = np.array([1,3])
print(a-b)         #벡터의 뺄셈

[ 1 -2]


In [9]:
print(2 * a)       #스칼라 값 곱셈 

[4 2]


In [10]:
b = np.array([1,3])
c = np.array([4,2])
print(b.dot(c))     #변수명1.dot(변수명2) 로 내적을 계산

10


In [11]:
a = np.array([1,3])
print(np.linalg.norm(a))   #np.linalg.norm()으로 벡터의 크기를 구할 수 있다.

3.1622776601683795


## 합의 기호

In [1]:
import numpy as np
a = np.ones(1000)  #[1 1 1 ... 1]
b = np.arange(1, 1001)   #[1 2 3 ... 1000]
print(a.dot(b))          #for문을 사용하지 않고 내적으로 계산

500500.0


## 미분

머신러닝은 결국 함수에서 최소나 최대인 입력을 찾는 문제(최적화 문제)입니다. 함수의 최저지점은 기울기가 0이되는 성질이 있으므로 이러한 문제를 풀려면 함수의 기울기를 아는 것이 중요